# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e8b4632a70986d3744d02e3dd1d0e0e4cf0746bba45f152af0a37a66e4ceb3c2a70b7a857a2103683ac13e83f1096103890270a8aef34897ba2d78f9fa40d412

test:
  secret_key_base: 3f1cd4f4b48621b9f2ce68c8e018eb4241a949e50e81b2ddca7f8d782eb4e0066f41fd5aaa6d3db616b38a1c453617992b0f9d5a4ae6443d7b023ed59462f326

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
